name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  buildx:
    name: Build and Publish images
    runs-on: "ubuntu-latest"

    env:
      ORG: "mitjaziv"
      IMAGE_NAME: "swagger-codegen-cli"
      TAG: "2.4.27"
      DOCKERFILE: "Dockerfile"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        continue-on-error: false
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{  secrets.DOCKERHUB_TOKEN }}

      - name: "Publish multi-platform docker image"
        if: github.ref == 'refs/heads/main'
        run: |
          docker buildx build --platform=linux/amd64,linux/arm64 -f ${DOCKERFILE} --push -t "${ORG}/${IMAGE_NAME}:${TAG}" -t "${ORG}/${IMAGE_NAME}:latest" .
